#!/usr/bin/env python3
"""Generate synthetic image embeddings for the HNSWlib tutorial.

Creates three binary files:
  - embeddings.bin : N_BASE  x DIM float32 vectors (simulating image features)
  - queries.bin    : N_QUERY x DIM float32 vectors
  - groundtruth.bin: N_QUERY x K   int32   labels  (brute-force exact top-K)

All vectors are unit-normalised so L2 distance is monotonic with cosine
similarity, which is realistic for image embeddings from models like
ResNet or CLIP.
"""

import argparse
import os
import struct
import sys

import numpy as np


def write_fvecs(path, vecs):
    """Write float32 matrix to a flat binary file (no header)."""
    vecs.astype(np.float32).tofile(path)


def write_ivecs(path, vecs):
    """Write int32 matrix to a flat binary file (no header)."""
    vecs.astype(np.int32).tofile(path)


def compute_groundtruth(base, queries, k):
    """Brute-force exact k-NN using L2 distance."""
    n_queries = queries.shape[0]
    gt = np.empty((n_queries, k), dtype=np.int32)

    batch = 256
    for start in range(0, n_queries, batch):
        end = min(start + batch, n_queries)
        q = queries[start:end]                       # (batch, dim)
        # ||q - b||^2 = ||q||^2 + ||b||^2 - 2 q.b
        dists = (
            np.sum(q ** 2, axis=1, keepdims=True)
            + np.sum(base ** 2, axis=1, keepdims=False)
            - 2.0 * q @ base.T
        )
        gt[start:end] = np.argpartition(dists, k, axis=1)[:, :k]

        if (start // batch) % 10 == 0:
            print(f"  groundtruth: {end}/{n_queries}", end="\r")

    print()
    return gt


def main():
    parser = argparse.ArgumentParser(description="Generate synthetic embeddings")
    parser.add_argument("--n_base",  type=int, default=50000,
                        help="Number of base vectors (default: 50000)")
    parser.add_argument("--n_query", type=int, default=5000,
                        help="Number of query vectors (default: 5000)")
    parser.add_argument("--dim",     type=int, default=768,
                        help="Embedding dimension (default: 768)")
    parser.add_argument("--k",       type=int, default=10,
                        help="Top-K for groundtruth (default: 10)")
    parser.add_argument("--output_dir", type=str, default="data",
                        help="Output directory (default: data)")
    parser.add_argument("--seed",    type=int, default=42,
                        help="Random seed (default: 42)")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)
    rng = np.random.default_rng(args.seed)

    # --- Generate clustered base vectors ---
    # Real image embeddings are clustered (similar images group together).
    # Pure random vectors in high dimensions are roughly equidistant, which
    # makes ANN search artificially hard.  We generate clusters around random
    # centroids so that nearby vectors actually share structure.
    n_clusters = 50
    print(f"Generating {args.n_base} base vectors (dim={args.dim}, "
          f"{n_clusters} clusters)...")
    centroids = rng.standard_normal((n_clusters, args.dim)).astype(np.float32)
    labels = rng.integers(0, n_clusters, size=args.n_base)
    base = centroids[labels] + 0.1 * rng.standard_normal(
        (args.n_base, args.dim)).astype(np.float32)
    norms = np.linalg.norm(base, axis=1, keepdims=True)
    base /= norms  # unit normalise

    # --- Generate query vectors (sampled from same clusters) ---
    print(f"Generating {args.n_query} query vectors...")
    q_labels = rng.integers(0, n_clusters, size=args.n_query)
    queries = centroids[q_labels] + 0.1 * rng.standard_normal(
        (args.n_query, args.dim)).astype(np.float32)
    norms = np.linalg.norm(queries, axis=1, keepdims=True)
    queries /= norms

    # --- Compute groundtruth ---
    print(f"Computing exact top-{args.k} groundtruth (brute force)...")
    gt = compute_groundtruth(base, queries, args.k)

    # --- Write header file so C++ knows the dimensions ---
    header_path = os.path.join(args.output_dir, "data_config.h")
    with open(header_path, "w") as f:
        f.write(f"// Auto-generated by generate_embeddings.py\n")
        f.write(f"#pragma once\n")
        f.write(f"#define DATA_N_BASE  {args.n_base}\n")
        f.write(f"#define DATA_N_QUERY {args.n_query}\n")
        f.write(f"#define DATA_DIM     {args.dim}\n")
        f.write(f"#define DATA_K       {args.k}\n")

    # --- Write binary files ---
    base_path = os.path.join(args.output_dir, "embeddings.bin")
    query_path = os.path.join(args.output_dir, "queries.bin")
    gt_path = os.path.join(args.output_dir, "groundtruth.bin")

    write_fvecs(base_path, base)
    write_fvecs(query_path, queries)
    write_ivecs(gt_path, gt)

    base_mb = os.path.getsize(base_path) / (1024 * 1024)
    query_mb = os.path.getsize(query_path) / (1024 * 1024)

    print(f"\nWritten to {args.output_dir}/:")
    print(f"  embeddings.bin   {args.n_base:>9,} x {args.dim}  ({base_mb:.1f} MB)")
    print(f"  queries.bin      {args.n_query:>9,} x {args.dim}  ({query_mb:.1f} MB)")
    print(f"  groundtruth.bin  {args.n_query:>9,} x {args.k}")
    print(f"  data_config.h    (C++ header with dimensions)")


if __name__ == "__main__":
    main()
